[General]
network = cashierQueues
sim-time-limit = 17h

**.entrance.interArrivalTime= exponential(25s)
**.numCashiers=7
**.numSelfCheckouts=3
**.entrance.stopTime =14.5h

# Checkouts
**.selfCheckouts[*].serviceTime = max(0s, normal(100s, 30s))
**.cashiers[*].serviceTime = max(0s, normal(120s, 40s))

# Receipt Checker
**.receiptChecker.serviceTime = uniform(1s, 3s)

#Data collection
# 1. Track Queue Lengths
**.cashierQueue.queueLength.recordVector = true
**.selfCheckoutQueue.queueLength.recordVector = true
**.receiptQueue.queueLength.recordVector = true

# 2. Track Waiting Times
**.cashierQueue.queueingTime.recordVector = true
**.selfCheckoutQueue.queueingTime.recordVector = true
**.receiptQueue.queueingTime.recordVector = true

# 3. Track Employee Utilization 
**.cashiers[*].busy.recordVector = true
**.selfCheckouts[*].busy.recordVector = true
**.receiptChecker.busy.recordVector = true

#Configurations
[Config Normal]
repeat=5

[Config Understaff]
repeat=5
**.numCashiers=3

[Config peakDay]
repeat=5
**.entrance.interArrivalTime= exponential(16.5s)

