[General]
network = cashierQueues
sim-time-limit = 17h
**.entrance.stopTime =14.5h

# Parameter names must match the NED submodule names exactly
**.entrance.interArrivalTime = exponential(25s)

# Parameters for the Server modules
**.selfCheckouts[*].serviceTime = normal(120s, 30s)
**.cashiers[*].serviceTime = normal(60s, 15s)

# Parameters for the Receipt Checker
**.receiptChecker.serviceTime = uniform(1s, 3s)

# ==========================================================
# TURN ON DATA COLLECTION FOR PROJECT GRAPHS
# ==========================================================
# 1. Track Queue Lengths (To prove if lines get too long)
**.cashierQueue.queueLength.recordVector = true
**.selfCheckoutQueue.queueLength.recordVector = true
**.receiptQueue.queueLength.recordVector = true

# 2. Track Waiting Times (To prove if customers wait > 10 mins)
**.cashierQueue.queueingTime.recordVector = true
**.selfCheckoutQueue.queueingTime.recordVector = true
**.receiptQueue.queueingTime.recordVector = true

# 3. Track Employee Utilization (To find the ideal number of staff)
**.cashiers[*].busy.recordVector = true
**.selfCheckouts[*].busy.recordVector = true
**.receiptChecker.busy.recordVector = true